apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  completions: 1
  template:
    metadata:
      name: kaniko
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: regcred
        secret:
          secretName: registry-secret
      - name: kaniko-context
        emptyDir: {}
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=Dockerfile"
          - "--context=git://$GIT_TOKEN@github.com/zawadimario/fastapi-actions-ci.git#refs/heads/kaniko-test"
          - "--destination=zawadimario/sample-api:v1.0.2"
          # - "--custom-platform=linux/amd64"
          # - "--custom-platform=linux/arm64"
          - "--snapshot-mode=redo"
          - "--ignore-var-run"
          - "--cleanup"
          - "--verbosity=info"
        env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: git-credentials
        volumeMounts:
        - name: kaniko-context
          mountPath: /context
        - name: regcred
          mountPath: /kaniko/.docker